//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDBan
    {
        public string MaHDBan { get; set; }
        public string MaHang { get; set; }
        public double SoLuong { get; set; }
        public double DonGia { get; set; }
        public double GiamGia { get; set; }
        public double ThanhTien { get; set; }
    }
}
