//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDBan
    {
        public string MaHDBan { get; set; }
        public string MaNhanVien { get; set; }
        public System.DateTime NgayBan { get; set; }
        public string MaKhach { get; set; }
        public double TongTien { get; set; }
    }
}
